### ISSUE TITLE
Secrets file not found

### ISSUE THREAD

**Issue by seventhis** [missaelcorm/cryptoCurrency#2]
Followed install steps thoroughly. Get the following error when url launches.
Suggestions?

![secrets error](https://user-images.githubusercontent.com/80498057/170851375-c7dbdfa6-bc51-44ff-a728-1b96140e15e3.png)

**Comment by missaelcorm** [comment]
You can try to create the "secrets.toml" file and add your API key. Or easier, you que can assign directly your API key to the variable.

Example.

YOUR_API_KEY = "123-api-key"

**Comment by seventhis** [comment]
okay thanks!

**Comment by seventhis** [comment]
resolved
